version = 0.1
[default.deploy.parameters]
stack_name = "sam-bug-tmp"
resolve_s3 = true
s3_prefix = "sam-bug-tmp"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
disable_rollback = true
image_repositories = []
